[package]
name = "halogen"
version = "0.1.0"
authors = ["Ben Brown <bbrown683@live.com>"]
description = "Rendering engine over gfx-hal"
edition = "2018"

[dependencies]
clap = "2.32.0"
directories = "1.0.2"
gfx-hal = { path = "gfx/src/hal", version = "0.1" }
gfx-backend-dx12 = { path = "gfx/src/backend/dx12", version = "0.1" }
gfx-backend-vulkan = { path = "gfx/src/backend/vulkan", version = "0.1" }
gltf = "0.11.2"
image = "0.20.0"
imgui = "0.0.21"
log = "0.4.6"
log4rs = "0.8.1"
nalgebra = "0.16.5"
num_cpus = "1.8.0"
rayon = "1.0.3"
rusttype = "0.7.2"
specs = "0.14.0"
winit = "0.17.2"