[package]
name = "halogen"
version = "0.1.0"
authors = ["Ben Brown <bbrown683@live.com>"]
description = "WIP game engine"
edition = "2018"

[dependencies]
ash = "0.26.0"
log = "0.4.6"
log4rs = "0.8.1"
winit = "0.17.2"